language: python
python:
    - "3.6"
install:
    - pip install pipenv
    - pipenv install --dev
script:
    pipenv run build
deploy:
    provider: pages
    skip-cleanup: true
    keep-history: true
    on:
        branch: master
